AMWSUP-17 Ansible Hub documentation link broken
ansible-middleware/janus pull request #38
Opened 2023-11-13 13:46 UTC by RanabirChakraborty

Issue: https://issues.redhat.com/browse/AMWSUP-17

EAP PR: https://github.com/ansible-middleware/wildfly/pull/161
JWS PR: https://github.com/ansible-middleware/jws/pull/258
keycloak PR: https://github.com/ansible-middleware/keycloak/pull/127
Infinispan PR: https://github.com/ansible-middleware/infinispan/pull/35
AMQ PR: https://github.com/ansible-middleware/amq/pull/107
jbcs PR: https://github.com/ansible-middleware/jbcs/pull/4

2023-11-14 08:55 UTC, guidograzioli requested changes

2023-11-14 08:55 UTC, guidograzioli commented on playbooks/amq_broker.yml
> +          * [`activemq`](https://console.redhat.com/ansible/automation-hub/repo/published/redhat/amq_broker/content/role/amq_broker/): Perform installation and configuration
the replacement happens after subsitutions, so this should be `* [amq_broker]` not `* [activemq]`

2023-11-14 08:55 UTC, guidograzioli commented on playbooks/data_grid.yml
> +          * [`infinispan`](https://console.redhat.com/ansible/automation-hub/repo/published/redhat/data_grid/content/role/data_grid/): performs an installation of Infinispan or DataGrid nodes or clus
same as above, data_grid and data_grid_cache

2023-11-14 08:55 UTC, guidograzioli commented on playbooks/sso.yml
> +          * [`keycloak`](https://console.redhat.com/ansible/automation-hub/repo/published/redhat/sso/content/role/sso/): role for installing the service.
`sso`, `sso_realm` and `sso_quarkus`

2023-11-15 07:24 UTC, RanabirChakraborty commented
Thanks! @guidograzioli Did the required changes.

2023-11-15 07:59 UTC, guidograzioli requested changes
Thanks for fixeing, but I am sorry there is another needed change that I didn't see yesterday. `roiles_paths` goes in the placeholder_delete OR in the  placehjolder_content, not both

2023-11-15 13:10 UTC, RanabirChakraborty commented
@guidograzioli I actually tested it and it worked fine for EAP/wildfly, it actually deleting the content inside [roles_paths](https://github.com/ansible-middleware/wildfly/commit/b19cc4e7bf3648122c488968745104cdcf2c692c#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L30-L39) and replacing it with [this](https://github.com/ansible-middleware/janus/pull/38/files#diff-a0685f63ed3654ca257627c0ba578c989dbdf3f02020fc9b7f35b9dbac2d58acR37-R43)

2023-11-15 14:41 UTC, guidograzioli approved these changes
LGTM

2023-11-15 14:41 UTC, merged